### ISSUE TITLE
3 errors I've found in littlewigs

### ISSUE THREAD

**Issue by wwbrandon** [BigWigsMods/LittleWigs#1176]
![image](https://github.com/user-attachments/assets/f8907da5-5197-4b4e-a67c-fd63bc66cea6)

![image](https://github.com/user-attachments/assets/8d90094c-ff3f-4a5f-b561-c8f111c33605)

The Radiant light buff won't allow to disable messages. Actually doubles the messages even when unchecked.

![image](https://github.com/user-attachments/assets/881b893e-0e4b-4462-a3ec-552d34e5bee4)

First Twilight Buffet on boss- timer inaccurate by almost 10 seconds.

Also, bar timer for Molten Spark for Forgemaster isn't working.

**Comment by ntowle** [comment]
The Radiant Light message spam is from Blizzard, not LittleWigs.

Blizzard changed Drahga's timers, this has now been fixed by https://github.com/BigWigsMods/LittleWigs/commit/b1810e5636d8da4c0416194a78c2dcfa2315171f. Thanks for reporting.

There is no separate timer for Molten Spark, it's applied as part of Molten Flurry.
