### ISSUE TITLE
Some abilities timer is not consistent

### ISSUE THREAD

**Issue by Abuhmeed** [BigWigsMods/LittleWigs#587]
## Describe the problem
the first boss in Halls of Atonement, he dose the ability [Refracted Sinlight], It's important as tank to track this ability, but the boss seem to always do it before bigwigs timer, the tracker still counts 3-4 seconds late

this happens with few more bosses in SL dungeons, not really sure if you are aware or not, thx for the good work

the difficulty is Mythic + 15s

here is a list of the bosses, ill update it when i remember the rest

-Boss Halkias, the Sin-Stained Goliath in HOA, Ability is [Refracted Sinlight]
-Boss Ingra Maloch in MOTS, ability is [Repulsive Visage]
-Boss Gorechop in TOP, ability is [Hateful Strike]
-Boss Xav the Unfallen, ability is [Brutal Combo]

### What steps will reproduce the problem?

1.  
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)
LittleWigs-v9.0.29

**Comment by funkydude** [comment]
1) Make reports in the correct project, LittleWigs in this case
2) Actually read and take action on the questions being asked. You didn't provide any useful information such as your LittleWigs version or dungeon difficulty, you just ignored those questions.
3) Vague complaints like "a few more bosses" are useless to us. Point out specific issues.

**Comment by Abuhmeed** [comment]
`Actually read and take action on the questions being asked. You didn't provide any useful information such as your LittleWigs version or dungeon difficulty, you just ignored those questions.`

sorry for lack the lack of information, I updated the post

**Comment by Abuhmeed** [comment]
are you aware of the issue that bosses timers or off for many abilities ?

**Comment by Zireael-N** [comment]
> the first boss in Halls of Atonement, he dose the ability [Refracted Sinlight], It's important as tank to track this ability, but the boss seem to always do it before bigwigs timer, the tracker still counts 3-4 seconds late

Please provide logs?

I spent my time looking through some:
- [HoA +24 @ Feb 09 2021](https://www.warcraftlogs.com/reports/DPnCKz1w4j3YkyNA#fight=1&type=summary&pins=2%24Off%24%23244F4B%24expression%24type%20%3D%20%22phasestart%22%20OR%20(source.id%20%3D%20165408%20AND%20type%20%3D%20%22cast%22%20AND%20ability.id%20!%3D%201)&view=events) (first cast - 38.39s since the pull, 2nd cast - 46.12s after)
- [HoA +23 @ Feb 22 2021](https://www.warcraftlogs.com/reports/MdZW7rKXTj2RQDYN#fight=2&type=summary&translate=true&pins=2%24Off%24%23244F4B%24expression%24type%20%3D%20%22phasestart%22%20OR%20(source.id%20%3D%20165408%20AND%20type%20%3D%20%22cast%22%20AND%20ability.id%20!%3D%201)&view=events) (first cast - 38.45s since the pull, 2nd cast - 46.04s after)
- [HoA +15 @ Feb 27 2021](https://www.warcraftlogs.com/reports/Nq6RbfHzAF7LcjyZ#fight=last&translate=true&pins=2%24Off%24%23244F4B%24expression%24type%20%3D%20%22phasestart%22%20OR%20(source.id%20%3D%20165408%20AND%20type%20%3D%20%22cast%22%20AND%20ability.id%20!%3D%201)&view=events)  (first cast - 38.46s since the pull, 2nd cast - 46.15s after)
- [HoA +13 @ Feb 27 2021](https://www.warcraftlogs.com/reports/bXfzj62dVBxvALND#fight=3&pins=2%24Off%24%23244F4B%24expression%24type%20%3D%20%22phasestart%22%20OR%20(source.id%20%3D%20165408%20AND%20type%20%3D%20%22cast%22%20AND%20ability.id%20!%3D%201)&view=events)  (first cast - 33.31s - **notice how this one is 5 seconds sooner** - since the pull, 2nd cast - 46.2s after)

We display a bar with 31s on the pull and 45s after each cast.

**Comment by Zireael-N** [comment]
> here is a list of the bosses, ill update it when i remember the rest
>
> -Boss Halkias, the Sin-Stained Goliath in HOA, Ability is [Refracted Sinlight]
> -Boss Ingra Maloch in MOTS, ability is [Repulsive Visage]
> -Boss Gorechop in TOP, ability is [Hateful Strike]
> -Boss Xav the Unfallen, ability is [Brutal Combo]

Again, please provide logs.
