### ISSUE TITLE
Nameplate bar and audio countdown issues.

### ISSUE THREAD

**Issue by Ghilean** [BigWigsMods/LittleWigs#615]
Hi.

While setting up alerts for dungeon I've noticed that certain options for several NPC abilities or abilities themselves are not present in the list. Reasons for them to be absent are not obvious to me. I apologize if they are.

Necrotic Wake:
Skeletal Marauder's Gruesome Cleave - not present
Stitched Vanguard's Bone Claw - not present
Kyrian Stitchwerk's Tenderize - audio timer doesn't work

Sanuine Depths:
Chamber Sentinel's Severing Slice - no nameplate bar option
Insatiable Brute's Slam - no nameplate bar option
Depths Warden's Crushing Strike - no nameplate bar option
Head Custodian Javlin's Bludgeoning Bash - no nameplate bar option

Theater Of Pain:
Xav's Brutal Combo - audio timer doesn't work
Putrid Butcher's Devour - not present
All minibosses in military quarter - not present
Nefarious Darkspeaker's abilities - not present

General issues:
Those are only the cases I've noticed as they are important for me as a tank. Though nameplate bars and audio countdown for trash - both seem to be more of a global issues relating to many other abilities.
I've tried to set up audio countdown for several abilities listed above: none of them worked.
Nameplate bar option isn't available for major number of abilities.

LittleWigs version 9.1.3
BigWigs version 232 (09476e5)
Russian WOW language

**Comment by ntowle** [comment]
Thanks for the report. Some of these were added over the course of Shadowlands and the rest are now legacy content with the impending release of Dragonflight so I'll close this out.

In general trash timers aren't as reliable since there's not a great way to reliably detect exactly when combat starts with an enemy, and often they don't live long enough for timers based on previous ability usages to be very useful.
