### ISSUE TITLE
Vortex Pinnacle - Asaad timers partially wrong

### ISSUE THREAD

**Issue by ljosberinn** [BigWigsMods/LittleWigs#912]
## Describe the problem

The first add spawns at the time LittleWigs currently displays the first Static Cling goes out. From there on I believe its entirely off on those 2 abilities:

https://www.warcraftlogs.com/reports/a:BW8qtFgMCnQxbcTa#fight=2&pull=22&hostility=1&type=casts&source=68&view=events

**Comment by ntowle** [comment]
From your log:

| Time | Since last | LW timer | Event |
|--------|--------|--------|--------|
| 25:24.077 | 0 | 0 | Encounter Start |
| 25:43.336 | 19.3 | 18.0 | Skyfall Nova 1 |
| 25:49.454 | 25.4 | 25.2 | Static Cling 1 |
| 26:22.231 | 38.9 | 38.9 | Skyfall Nova 2 |
| 26:28.314 | 38.9 | 28.3 | Static Cling 2 (delayed by Supremacy of the Storm) | 
| 26:47.717 | 25.5 | 25.5 | Skyfall Nova 2 |
| 26:57.433 | 29.1 | 28.3 | Static Cling 3 |

So the timers seem more or less accurate compared to the log you provided. Unfortunately this boss does suffer from some spell queueing issues especially with the extra-long Supremacy of the Storm cast sequence where several abilities can queue up. I will take look at adjusting currently running timers based on other casts.

**Comment by ljosberinn** [comment]
hmm the weird part is, the very first static cling cast as indicated by littlewigs will actually be an add a couple seconds later - before any supremacy of the storm cast

**Comment by ntowle** [comment]
Are you saying you had a second add before the first Supremacy combo? I only see the one in the log which happens shortly before the first Static Cling. But I will recheck it either way.

**Comment by ljosberinn** [comment]
no, littlewigs will indicate you get a static cling cast around idk, 15seconds in. 

the boss will instead spawn an add a couple seconds later (row 2 of your table). there's no static cling before an add spawns.

x-referencing with the Asaad.lua however it looks like you have accounted for this so it might for some reason be something else interfering here... I'll try to get a screenshot next time

**Comment by ntowle** [comment]
> no, littlewigs will indicate you get a static cling cast around idk, 15seconds in.
> the boss will instead spawn an add a couple seconds later (row 2 of your table). there's no static cling before an add spawns.

It's not coded to do that, I can't find any videos of that behavior online, and it doesn't happen to me when I run it. If you can get some video or screenshot of this happening I can take a look. Else there's not much I can do here.

Adjusted timers in e0772c93819db707e79b6c643e55cf6a0eceff61, timer for Static Cling and Skyfall Nova should be more accurate after Supremacy of the Storm (it's now restarting timers instead, avoiding pausing for long periods).
